version: "3.8"
services:
  postgresdb:
    image: postgres:15.2-alpine
    container_name: golang-api-postgresdb
    environment:
      POSTGRES_USER: golang-api
      POSTGRES_PASSWORD: golang-api
      POSTGRES_DB: golang-api
    ports:
    - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

 
volumes:
  pgdata:
 