definitions:
  models.App:
    properties:
      androidVer:
        type: string
      category:
        type: string
      contentRating:
        type: string
      currentVer:
        type: string
      genres:
        type: string
      installs:
        type: string
      lastUpdated:
        type: string
      name:
        type: string
      price:
        type: string
      rating:
        maximum: 5
        minimum: 0
        type: number
      reviews:
        minimum: 0
        type: integer
      size:
        type: string
      type:
        type: string
    required:
    - androidVer
    - category
    - contentRating
    - currentVer
    - genres
    - installs
    - lastUpdated
    - name
    - price
    - size
    - type
    type: object
  utils.JSONResponse:
    properties:
      data: {}
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/apps:
    get:
      consumes:
      - application/json
      description: Get a list of apps with pagination and filters
      parameters:
      - default: 10
        description: Limit
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset
        in: query
        name: offset
        type: integer
      - description: Price Filter
        in: query
        name: priceFilter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.App'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: List apps
      tags:
      - apps
  /api/v1/apps/:name:
    delete:
      description: Delete all reviews for a given app name
      parameters:
      - description: App name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Reviews deleted successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: Delete reviews for an app
      tags:
      - reviews
  /api/v1/reviews/:name:
    delete:
      description: Delete all reviews for a given app name
      parameters:
      - description: App name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Reviews deleted successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: Delete reviews for an app
      tags:
      - reviews
swagger: "2.0"
