definitions:
  models.NullableFloat64:
    properties:
      valid:
        type: boolean
      value:
        type: number
    type: object
  models.Review:
    properties:
      app:
        type: string
      id:
        type: integer
      sentiment:
        type: string
      sentiment_polarity:
        $ref: '#/definitions/models.NullableFloat64'
      sentiment_subjectivity:
        $ref: '#/definitions/models.NullableFloat64'
      translated_review:
        type: string
    required:
    - app
    - sentiment
    - translated_review
    type: object
  utils.JSONResponse:
    properties:
      data: {}
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/reviews/{id}:
    put:
      consumes:
      - application/json
      description: Updates an existing review in the database.
      parameters:
      - description: Review ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated review data
        in: body
        name: review
        required: true
        schema:
          $ref: '#/definitions/models.Review'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Review'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: Update Review
      tags:
      - Reviews
swagger: "2.0"
